repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
      - id: check-yaml
        name: Check YAML syntax
      - id: check-added-large-files
        name: Check for large files
        args: [--maxkb=1000]
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-toml
        name: Check TOML syntax
      - id: check-json
        name: Check JSON syntax
      - id: mixed-line-ending
        name: Check mixed line endings
        args: [--fix=lf]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff
        name: Ruff linter
        args: [--fix, --unsafe-fixes, --exit-non-zero-on-fix]
        types_or: [python, pyi]

      - id: ruff-format
        name: Ruff formatter
        types_or: [python, pyi]
