[project]
name = "zeil-tech-task"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "opensearch-py>=3",
    "sentence-transformers>=3.0",
    "numpy>=1.26",
    "setuptools>=82.0.1",
    "pydantic-settings>=2.14.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.15"
]

[project.scripts]
zeil = "zeil.cli:main"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 120
fix = true


[tool.ruff.lint]
select = [
    "I",
    "F",
    "S",
    "PLC",
    "W",
    "B",
    "BLE",
    "UP",
    "N",
    "ERA",
]

[tool.ruff.lint.per-file-ignores]
"**/tests/**" = [
    "S101",
    "S105",
    "S106",
    "S108",
    "BLE001",
]

[tool.ruff.format]
quote-style = "single"
line-ending = "auto"

[tool.ruff.lint.isort]
length-sort-straight = true
lines-between-types = 1
